version: "3.7"

services:
  db:
    image: orientdb:3.0.27
    command: dserver.sh
    volumes:
      - ./var/odb/config:/orientdb/config
      - ./var/odb/databases:/orientdb/databases
    environment:
      ORIENTDB_ROOT_PASSWORD: root
      ORIENTDB_NODE_NAME: odb
    ports:
      - "127.0.0.1:2480:2480"
      - "127.0.0.1:2424:2424"
  api:
    depends_on: [db]
    build:
      context: ./api
    volumes:
      - ./api:/app
    ports:
      - "127.0.0.1:4000:4000"
  www:
    depends_on: [api]
    build:
      context: ./www
    environment:
      - PORT=3000
      - NODE_ENV=production
      - API=127.0.0.1:4000
    ports:
      - "127.0.0.1:3000:3000"
  e2e:
    image: codeception/codeceptjs
