FROM node:13-alpine AS builder
WORKDIR /www
COPY package.json .
RUN yarn
COPY . .
RUN yarn build && yarn --production

FROM node:13-alpine
WORKDIR /www
COPY --from=builder /www .
EXPOSE 3000
CMD ["node_modules/.bin/next", "start"]