name: Prebuild, Run, Test, Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Run prebuild test
        run: make prebuild
      - name: Run docker-compose
        if: success()
        env:
          STAGE: "prod"
        run: make up-ci
      - name: Run e2e tests
        if: success()
        run: make e2e
      - name: Run lighthouse
        if: success()
        uses: treosh/lighthouse-ci-action@v2
        with:
          configPath: "lighthouse-config.json"
          urls: http://localhost:3000
      - name: Release
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
